import { faker } from '@faker-js/faker';

import { JokesData } from '@/models/user/JokesData';

/**
 * The function creates random joke data by generating a random string using the faker library.
 * @returns an object of type JokesData. The object has a property "joke" which is assigned a random
 * string value generated by the faker.string.sample(5) function.
 */
export function createRandomJokeData(): JokesData {
  return {
    joke: faker.string.sample(5),
  };
}
